### ISSUE TITLE
Failed to match indirect branch when BOLT AArch64 binary

### ISSUE THREAD

**Issue by wade901** [facebookincubator/BOLT#111]
Hello,

When I'm trying to use BOLT to optimize an AArch64 application, BOLT aborted when analyze indirect branch fragments. The indirect branch code as follows. Has BOLT support all the patterns of AArch64 indirect branch already?

```
         652ec8:       900001e6        adrp    x6, 68e000 <plone+0x18>
         652ecc:       9121c0c6        add     x6, x6, #0x870
         652ed0:       8b0e08c6        add     x6, x6, x14, lsl #2
         652ed4:       b94000c7        ldr     w7, [x6]
         652ed8:       8b27c0c6        add     x6, x6, w7, sxtw
         652edc:       d61f00c0        br      x6
```
```
      4716dc:   b000171c    adrp    x28, 752000 <__func__.6103+0x120>
      ......
      4716e4:   91188380    add x0, x28, #0x620
      ......
      4716f0:   9e67000a    fmov    d10, x0
      ......
      4717b8:   9e660141    fmov    x1, d10
      4717bc:   78605820    ldrh    w0, [x1,w0,uxtw #1]
      4717c0:   10000061    adr x1, 4717cc <intr_thread_main+0x23c>
      4717c4:   8b20a820    add x0, x1, w0, sxth #2
      4717c8:   d61f0000    br  x0
```

  Stack Backtrace:
 
```
#0  0x00007ffff6f03277 in raise () from /lib64/libc.so.6
#1  0x00007ffff6f04968 in abort () from /lib64/libc.so.6
#2  0x000000000175f790 in llvm::llvm_unreachable_internal (msg=0x2ecc498 "Failed to match indirect branch! (fragment 2)",
    file=0x2ecbc70 "llvm/tools/llvm-bolt/src/Target/AArch64/AArch64MCPlusBuilder.cpp", line=507)
    at llvm/lib/Support/ErrorHandling.cpp:222
#3  0x00000000018207a1 in (anonymous namespace)::AArch64MCPlusBuilder::analyzeIndirectBranchFragment (this=0x41231f0, Inst=...,
    UDChain=..., JumpTable=@0x7fffffffcc60: 0x7fffffffcc80, Offset=@0x7fffffffcc68: 4341102,
    ScaleValue=@0x7fffffffcc70: 243878096, PCRelBase=@0x7fffffffcc38: 0x7fffffffce60)
    at llvm/tools/llvm-bolt/src/Target/AArch64/AArch64MCPlusBuilder.cpp:507
#4  0x00000000018216a6 in (anonymous namespace)::AArch64MCPlusBuilder::analyzeIndirectBranch (this=0x41231f0, Instruction=...,
    Begin=..., End=..., PtrSize=8, MemLocInstrOut=@0x7fffffffce40: 0x0, BaseRegNumOut=@0x7fffffffce34: 0,
    IndexRegNumOut=@0x7fffffffce30: 0, DispValueOut=@0x7fffffffce28: 0, DispExprOut=@0x7fffffffce20: 0x0, PCRelBaseOut=
    @0x7fffffffce18: 0xc5622a <llvm::decodeInstruction<unsigned int>(uint8_t const*, llvm::MCInst&, unsigned int, uint64_t, void const*, llvm::MCSubtargetInfo const&)+1780>)
    at llvm/tools/llvm-bolt/src/Target/AArch64/AArch64MCPlusBuilder.cpp:680
#5  0x00000000004971d9 in llvm::bolt::BinaryFunction::processIndirectBranch (this=0x45613d8, Instruction=..., Size=4,
    Offset=636, TargetAddress=@0x7fffffffd038: 0) at llvm/tools/llvm-bolt/src/BinaryFunction.cpp:718
#6  0x000000000049a091 in llvm::bolt::BinaryFunction::disassemble (this=0x45613d8)
    at llvm/tools/llvm-bolt/src/BinaryFunction.cpp:1271
#7  0x00000000005e8312 in llvm::bolt::RewriteInstance::disassembleFunctions (this=0x7fffffffd990)
    at llvm/tools/llvm-bolt/src/RewriteInstance.cpp:2742
#8  0x00000000005daf59 in llvm::bolt::RewriteInstance::run (this=0x7fffffffd990)
    at llvm/tools/llvm-bolt/src/RewriteInstance.cpp:797
#9  0x00000000004103a0 in main (argc=11, argv=0x7fffffffe238) at llvm/tools/llvm-bolt/src/llvm-bolt.cpp:323
```

**Comment by rafaelauler** [comment]
No, AArch64 BOLT doesn't support all possible indirect branch fragments. Our AArch64 port is experimental, but I see in your log this message:

BOLT-WARNING: non-relocation mode for AArch64 is not fully supported

Did you try a binary with relocations?

That said, the AArch64 port is far less mature than the X86 one and is also more challenging to support. Because of the RISC nature of it, there is less semantic encoded in each instruction and the compiler will frequently need to use multiple instructions to perform the same action that, in X86, would be a single instruction. This requires BOLT to match and recognize patterns spanning multiple instructions. That's tricky because the pattern may be spread in different basic blocks, which requires a dataflow analysis to track the relationship of the instructions across the entire CFG. But we can't build the complete CFG without understanding the indirect branches in the function. That's why it's a bit more involved to properly disassemble and reconstruct the CFG of a RISC binary. What we currently have implemented for AArch64 is a best effort strategy that worked well for gcc-generated binaries, but we can't guarantee will always work.

Yet, relocations for AArch64 are mandatory to properly recognize ADRP /ADR pairs. If you lack relocations, we won't understand that an ADRP instruction is trying to build the address of, say, ObjectX. We will have a partial view that ADRP is accessing the page of ObjectX and will create references against Page(ObjectX) instead of ObjectX. This will cause us to potentially link incorrectly depending on where Page(ObjectX) lands (in a different, unrelated section, for example).
